### ISSUE TITLE
Every slide have it's own header.

### ISSUE THREAD

**Issue by maxmas** [olivierbossel/slidizle#2]
Hello,

I like this script.
I have a suggestion, if every slide can set it's own header (title and text), 
that's great.
How do you think?

**Comment by olivierbossel** [comment]
Hi man,
Thanks for your feedback.
The idea of slidizle is to not force a certain display for you or to inject some predefined html for you. If you need some title and text as a header, you can do it with your own html like this for example :

```html
<div data-slidizle>
	<ul data-slidizle-content>
		<li>
			<header>
				<h3>My cool title</h3>
				<p>Donec at libero aliquet, fermentum leo non, blandit justo. Vivamus.</p>
			</header>
			<img src="..." />
		</li>
		<li>
			<header>
				<h3>My cool title</h3>
				<p>Donec at libero aliquet, fermentum leo non, blandit justo. Vivamus.</p>
			</header>
			<img src="..." />
		</li>
		<!-- etc... -->
	</ul>
</div>
```

Then you can handle the display as you want..
Is that the answer you where looking to or maybe I don't understand your point well..

Let me know!

Cheers!

**Comment by maxmas** [comment]
Hi,
Thank you very much!!  You solved my problem.
I originally thought that the title is fixed, can not switch with slider.
This is great, thanks again.

**Comment by olivierbossel** [comment]
No problem man, cheers!
